Word2Vec developed by Google researchers in 2013, Word2vec is a technique for generating word embeddings, which are numerical representations of words. The core idea is that words with similar meanings tend to appear in similar contexts, and Word2vec captures these relationships by placing their vectors closer together in a multi-dimensional space. It has dimension of 300.

In [2]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 68.1 MB/s eta 0:00:00


In [3]:
import gensim.downloader as api
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
print(model['apple'])

[-0.06445312 -0.16015625 -0.01208496  0.13476562 -0.22949219  0.16210938
  0.3046875  -0.1796875  -0.12109375  0.25390625 -0.01428223 -0.06396484
 -0.08056641 -0.05688477 -0.19628906  0.2890625  -0.05151367  0.14257812
 -0.10498047 -0.04736328 -0.34765625  0.35742188  0.265625    0.00188446
 -0.01586914  0.00195312 -0.35546875  0.22167969  0.05761719  0.15917969
  0.08691406 -0.0267334  -0.04785156  0.23925781 -0.05981445  0.0378418
  0.17382812 -0.41796875  0.2890625   0.32617188  0.02429199 -0.01647949
 -0.06494141 -0.08886719  0.07666016 -0.15136719  0.05249023 -0.04199219
 -0.05419922  0.00108337 -0.20117188  0.12304688  0.09228516  0.10449219
 -0.00408936 -0.04199219  0.01409912 -0.02111816 -0.13476562 -0.24316406
  0.16015625 -0.06689453 -0.08984375 -0.07177734 -0.00595093 -0.00482178
 -0.00089264 -0.30664062 -0.0625      0.07958984 -0.00909424 -0.04492188
  0.09960938 -0.33398438 -0.3984375   0.05541992 -0.06689453 -0.04467773
  0.11767578 -0.13964844 -0.26367188  0.17480469 -0.

In [5]:
len(model["apple"]) ## showing 300 dimesions

300

In [7]:
## sementic meaning capturing example

model.most_similar(positive =['king','woman'], negative = ['man'], topn= 5)

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581)]

In [9]:
## calculating similariy scores
print(model.similarity('woman', 'man'))
print(model.similarity('king', 'apple'))


0.76640123
0.10826096


## Creating Token embedding from Token IDS

In [15]:
import torch
input_ids= torch.tensor([2,3,5,1]) ## using small vocabulary
vocab_size = 6
output_dim= 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size,output_dim) ## intiating an embedding layer with random values
embedding_layer.weight



Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

Above Weight matrix of the embedding layer contain small and random values which will be optimized during the LLM training as a part of LLM optimization itself.

In [16]:
embedding_layer(torch.tensor([3])) ## printing embedding using token ids

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [17]:
embedding_layer(input_ids) ## prints 2,3,5,1 token ids embedding layer ## basically its a lookup operation which retrieves tokens using token ids

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)